apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: counterfeitcrisis-com-tls
spec:
  secretName: counterfeitcrisis-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: counterfeitcrisis.com
  dnsNames:
    - counterfeitcrisis.com
    - www.counterfeitcrisis.com